name: monitoring-prod

meta:
  grafana:
    user: ~
    pass: ~
  influxdb:
    user: ~
    password: ~
    database: ~
  riemann:
    pagerduty_api_key: ~
  network:
    range: ~
    reserved: ~
    static: ~
    dns: ~
    gateway: ~
    subnet: ~
    security_groups: ~

director_uuid: (( merge ))

releases:
- name: grafana
  version: 3+dev.1
- name: influxdb
  version: 5
- name: riemann
  version: 0.16.1

networks:
  - name: monitoring
    type: manual
    subnets:
      - range: (( meta.network.range ))
        reserved: (( meta.network.reserved ))
        gateway: (( meta.network.gateway ))
        dns: (( meta.network.dns ))
        static: (( meta.network.static ))
        cloud_properties:
          security_groups: (( meta.network.security_groups ))
          subnet: (( meta.network.subnet ))

jobs:
- name: monitoring
  templates:
  - {name: grafana, release: grafana}
  - {name: riemann, release: riemann}
  instances: 1
  resource_pool: medium_z1
  persistent_disk: 30000
  networks:
  - name: monitoring
    static_ips: (( static_ips(0) ))

- name: influxdb
  templates:
  - {name: influxdb, release: influxdb}
  instances: 1
  resource_pool: medium_z1
  persistent_disk: 500000
  networks:
  - name: monitoring
    static_ips: (( static_ips(1) ))

properties:
  env: monitoring
  grafana:
    admin_username: (( meta.grafana.user ))
    admin_password: (( meta.grafana.pass ))
    listen_port: 3000
    root_url: https://grafana-prod.18f.gov
    datasource:
      database_type: "influxdb"
      database_name: (( meta.influxdb.database ))
      url: (( "http://" jobs.influxdb.networks.monitoring.static_ips.[0] ":8086" ))
      name: "influxdb_production"
      user: (( meta.influxdb.user ))
      password: (( meta.influxdb.password ))

  influxdb:
    database: (( meta.influxdb.database ))
    user: (( meta.influxdb.user ))
    password: (( meta.influxdb.password ))
  riemann:
    pagerduty_api_key: (( meta.riemann.pagerduty_api_key ))
    swap:
      critical: 25
      warn: 10
    disk:
      critical: 90
      warn: 85
    influxdb:
      host: (( jobs.influxdb.networks.monitoring.static_ips.[0] ))
      username: (( meta.influxdb.user ))
      password: (( meta.influxdb.password ))
      port: 8086
      database: (( meta.influxdb.database ))
  hm:
    cloud_watch_enabled: true

resource_pools:
- name: medium_z1
  network: monitoring
  size: 2
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 30000
      type: gp2
    availability_zone: us-east-1b

compilation:
  network: monitoring
  reuse_compilation_vms: true
  workers: 4
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 30000
      type: gp2
    availability_zone: us-east-1b

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000

