name: monitoring-prod

meta:
  collectd:
    riemann_server: ~
  environment: ~
  grafana:
    user: ~
    pass: ~
    influxdb_user: ~
    influxdb_password: ~
    auth:
      github:
        client_id: ~
        client_secret: ~
        allowed_organizations: ~
        team_ids: ~
  influxdb:
    user: ~
    password: ~
    database: ~
  riemann:
    pagerduty_api_key: ~
    influxdb_user: ~
    influxdb_password: ~
  network:
    range: ~
    reserved: ~
    static: ~
    dns: ~
    gateway: ~
    subnet: ~
    security_groups: ~
  elbs: []

director_uuid: (( merge ))

releases:
- name: grafana
  version: latest
- name: influxdb
  version: latest
- name: riemann
  version: latest
- name: collectd
  version: latest

networks:
  - name: monitoring
    type: manual
    subnets:
      - range: (( meta.network.range ))
        reserved: (( meta.network.reserved ))
        gateway: (( meta.network.gateway ))
        dns: (( meta.network.dns ))
        static: (( meta.network.static ))
        cloud_properties:
          security_groups: (( meta.network.security_groups ))
          subnet: (( meta.network.subnet ))

jobs:
- name: monitoring
  templates:
  - {name: grafana, release: grafana}
  - {name: riemann, release: riemann}
  instances: 1
  resource_pool: grafana_z1
  persistent_disk: 30000
  networks:
  - name: monitoring
    static_ips: (( static_ips(0) ))

- name: influxdb
  templates:
  - {name: influxdb, release: influxdb}
  - {name: collectd, release: collectd}
  instances: 1
  resource_pool: large_z1
  persistent_disk: 500000
  networks:
  - name: monitoring
    static_ips: (( static_ips(1) ))

properties:
  env: monitoring
  collectd:
    hostname_prefix: (( meta.environment "." ))
    riemann_server: (( meta.collectd.riemann_server ))
  grafana:
    admin_username: (( meta.grafana.user ))
    admin_password: (( meta.grafana.pass ))
    listen_port: 3000
    root_url: https://metrics.cloud.gov
    auth:
      github:
        enabled: true
        client_id: (( meta.grafana.auth.github.client_id ))
        client_secret: (( meta.grafana.auth.github.client_secret ))
        allowed_sign_up: true
        auth_url: https://github.com/login/oauth/authorize
        token_url: https://github.com/login/oauth/access_token
        api_url: https://api.github.com/user
        team_ids: (( meta.grafana.auth.github.team_ids ))
        allowed_organizations: (( meta.grafana.auth.github.allowed_organizations ))
    datasources:
      - database_type: "influxdb"
        database_name: (( meta.influxdb.database ))
        url: (( "http://" jobs.influxdb.networks.monitoring.static_ips.[0] ":8086" ))
        name: "influxdb_production"
        user: (( meta.grafana.influxdb_user ))
        password: (( meta.grafana.influxdb_password ))
    dashboards:
      - path: dashboards/all-in-one-cf-components-dashboard.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/cloud-controller.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/dea.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/doppler-server.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/gorouter.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/metron-agent.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/syslog.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/traffic-controller.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/uaa.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring
      - path: dashboards/etcd.json
        branch: master
        repo_url: https://raw.githubusercontent.com/18F/cg-deploy-monitoring

  influxdb:
    database: (( meta.influxdb.database ))
    user: (( meta.influxdb.user ))
    password: (( meta.influxdb.password ))
  riemann:
    pagerduty_api_key: (( meta.riemann.pagerduty_api_key ))
    swap:
      critical: 25
      warn: 10
    disk:
      critical: 90
      warn: 85
    influxdb:
      host: (( jobs.influxdb.networks.monitoring.static_ips.[0] ))
      username: (( meta.riemann.influxdb_user ))
      password: (( meta.riemann.influxdb_password ))
      port: 8086
      database: (( meta.influxdb.database ))

resource_pools:
- name: grafana_z1
  network: monitoring
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: t2.medium
    elbs: (( meta.elbs ))
    ephemeral_disk:
      size: 30000
      type: gp2
    availability_zone: us-east-1b
- name: large_z1
  network: monitoring
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m4.large
    ephemeral_disk:
      size: 30000
      type: gp2
    availability_zone: us-east-1b


compilation:
  network: monitoring
  reuse_compilation_vms: true
  workers: 4
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 30000
      type: gp2
    availability_zone: us-east-1b

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000

