---
jobs:
- name: deploy-monitoring-staging
  plan:
  - aggregate:
    - get: monitoring-config
      trigger: true
    - get: common
      resource: common-staging
      trigger: true
    - get: pipeline-tasks
    - get: influxdb-release
    - get: grafana-release
    - get: cg-s3-riemann-release
    - get: cg-s3-collectd-release
    - get: cg-s3-encrypt-blobstore-release
    - get: monitoring-stemcell
      trigger: true
    - get: terraform-state
      resource: state-file-tooling
      trigger: true
    - get: cg-s3-cron-release
  - task: terraform-state-to-yaml
    file: pipeline-tasks/terraform-state-to-yaml.yml
    params:
      STATE_FILE: terraform.tfstate
  - task: monitoring-manifest
    config: &manifest-config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: 18fgsa/concourse-task
      inputs:
      - name: monitoring-config
      - name: terraform-yaml
      - name: common
      outputs:
      - name: monitoring-manifest
      run:
        path: sh
        args:
        - -exc
        - |
          monitoring-config/generate-manifest.sh \
            monitoring-config/monitoring-terraform-staging.yml \
            terraform-yaml/state.yml \
            common/secrets.yml \
            > monitoring-manifest/manifest.yml
  - put: monitoring-staging-deployment
    params: &deploy-params
      cert: common/boshCA.crt
      manifest: monitoring-manifest/manifest.yml
      releases:
      - influxdb-release/*.tgz
      - grafana-release/*.tgz
      - cg-s3-riemann-release/riemann*.tgz
      - cg-s3-collectd-release/collectd*.tgz
      - cg-s3-encrypt-blobstore-release/encrypt-blobstore-*.tgz
      - cg-s3-cron-release/cron-*.tgz
      stemcells:
      - monitoring-stemcell/*.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy monitoring on staging
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed monitoring on staging
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

- name: deploy-monitoring-production
  serial: true
  plan:
  - aggregate:
    - get: monitoring-staging-deployment
      passed: [deploy-monitoring-staging]
    - get: monitoring-config
      passed: [deploy-monitoring-staging]
      trigger: true
    - get: common
      resource: common-production
      trigger: true
    - get: pipeline-tasks
      passed: [deploy-monitoring-staging]
    - get: influxdb-release
      passed: [deploy-monitoring-staging]
    - get: grafana-release
      passed: [deploy-monitoring-staging]
    - get: cg-s3-riemann-release
      passed: [deploy-monitoring-staging]
    - get: cg-s3-collectd-release
      passed: [deploy-monitoring-staging]
    - get: cg-s3-encrypt-blobstore-release
      passed: [deploy-monitoring-staging]
    - get: monitoring-stemcell
      passed: [deploy-monitoring-staging]
      trigger: true
    - get: cg-s3-cron-release
      passed: [deploy-monitoring-staging]
    - get: terraform-state
      resource: state-file-tooling
      trigger: true
  - task: monitoring-manifest
    config:
      <<: *manifest-config
      run:
        path: sh
        args:
        - -exc
        - |
          monitoring-config/generate-manifest.sh \
            monitoring-config/monitoring-terraform-production.yml \
            terraform-yaml/state.yml \
            common/secrets.yml \
            > monitoring-manifest/manifest.yml
  - put: monitoring-production-deployment
    params: *deploy-params
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy monitoring on production
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed monitoring on production
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

resources:
- name: common-staging
  type: cg-common
  source:
    region: {{monitoring-staging-private-region}}
    bucket_name: {{monitoring-staging-private-bucket}}
    access_key_id: {{ci-access-key-id}}
    secret_access_key: {{ci-secret-access-key}}
    secrets_file: monitoring-staging.yml
    secrets_passphrase: {{monitoring-staging-private-passphrase}}
    bosh_cert: bosh-tooling.pem

- name: common-production
  type: cg-common
  source:
    region: {{monitoring-production-private-region}}
    bucket_name: {{monitoring-production-private-bucket}}
    access_key_id: {{monitoring-production-private-access-key-id}}
    secret_access_key: {{monitoring-production-private-secret-access-key}}
    secrets_file: monitoring-production.yml
    secrets_passphrase: {{monitoring-production-private-passphrase}}
    bosh_cert: bosh-tooling.pem

- name: cg-s3-collectd-release
  type: s3
  source:
    region_name: {{s3-bosh-releases-region}}
    access_key_id: {{ci-access-key-id}}
    bucket: {{s3-bosh-releases-bucket}}
    private: true
    regexp: collectd-(.*).tgz
    secret_access_key: {{ci-secret-access-key}}

- name: influxdb-release
  type: bosh-io-release
  source:
    repository: vito/influxdb-boshrelease

- name: grafana-release
  type: bosh-io-release
  source:
    repository: vito/grafana-boshrelease

- name: cg-s3-riemann-release
  type: s3
  source:
    region_name: {{s3-bosh-releases-region}}
    access_key_id: {{ci-access-key-id}}
    bucket: {{s3-bosh-releases-bucket}}
    private: true
    regexp: riemann-(.*).tgz
    secret_access_key: {{ci-secret-access-key}}

- name: cg-s3-encrypt-blobstore-release
  type: s3
  source:
    region_name: {{s3-bosh-releases-region}}
    access_key_id: {{ci-access-key-id}}
    bucket: {{s3-bosh-releases-bucket}}
    private: true
    regexp: encrypt-blobstore-(.*).tgz
    secret_access_key: {{ci-secret-access-key}}

- name: cg-s3-cron-release
  type: s3
  source:
    region_name: {{s3-bosh-releases-region}}
    access_key_id: {{ci-access-key-id}}
    bucket: {{s3-bosh-releases-bucket}}
    private: true
    regexp: cron-(.*).tgz
    secret_access_key: {{ci-secret-access-key}}


- name: monitoring-config
  type: git
  source:
    uri: {{cg-deploy-monitoring-git-url}}
    branch: {{cg-deploy-monitoring-git-branch}}

- name: monitoring-stemcell
  type: s3
  source:
    access_key_id: {{ci-access-key-id}}
    bucket: cg-stemcell-images
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz
    region_name: us-gov-west-1
    secret_access_key: {{ci-secret-access-key}}

- name: monitoring-staging-deployment
  type: 18f-bosh-deployment
  source:
    target: {{monitoring-staging-deployment-bosh-target}}
    username: {{monitoring-staging-deployment-bosh-username}}
    password: {{monitoring-staging-deployment-bosh-password}}
    deployment: {{monitoring-staging-deployment-bosh-deployment}}
    ignore_ssl: false

- name: monitoring-production-deployment
  type: 18f-bosh-deployment
  source:
    target: {{monitoring-production-deployment-bosh-target}}
    username: {{monitoring-production-deployment-bosh-username}}
    password: {{monitoring-production-deployment-bosh-password}}
    deployment: {{monitoring-production-deployment-bosh-deployment}}
    ignore_ssl: false

- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

- name: state-file-tooling
  type: s3-iam
  source:
    bucket: {{tf-state-bucket-tooling}}
    versioned_file: {{tf-state-file-tooling}}
    region_name: {{aws-region}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: 18f-bosh-deployment
  type: docker-image
  source:
    repository: 18fgsa/bosh-deployment-resource
- name: cg-common
  type: docker-image
  source:
    repository: 18fgsa/cg-common-resource
- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource


